default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: todoapp3 
  password: password123
  host: localhost

development:
  <<: *default
  database: todoapp3_development

test:
  <<: *default
  database: todoapp3_test

production:
  <<: *default
  database: todoapp3_production
  username: todoapp3
  password: <%= ENV["TODOAPP3_DATABASE_PASSWORD"] %>
  host: localhost
